name: push_bonds_daily

env:
  PYTHON_VERSION: "3.8" # set this to the Python version to use
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  schedule:
    - cron: '30 2 * * *' # 每天 UTC 时间 00:00 触发, 即上海时间9点

jobs:
  daily-push:
    runs-on: ubuntu-latest
    env:
      SERVERCHAN_API_KEY: ${{ secrets.SERVERCHAN_API_KEY }}

    permissions:
      issues: write
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Install dependencies
        run: pip install requests datetime

      - name: PUSH BONDS DAILY
        run: python bonds.py
